version: '3'

services:
  mysql:
    container_name: mysql-server
    image: mysql/mysql-server:8.0
    command: --authentication_policy=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
    networks:
      - default

  zeppelin:
    container_name: zeppelin
    image: apache/zeppelin:0.11.2
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "8080:8080"
    volumes:
      - ./zeppelin/notebooks:/zeppelin/notebooks
    networks:
      - default


  init-mysql:
    container_name: init-mysql-server
    platform: linux/arm64/v8
    build:
      context: ./init-mysql
    image: iitns/init-mysql:latest
    command: ["/app/init.sh"]
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - default


networks:
  default:
    name: mysql-zeppelin
